### ISSUE TITLE
diff-removed face is dark text on a dark background

### ISSUE THREAD

**Issue by dakrone** [philiparvidsson/emacs-github-theme#7]
The `diff-removed` face is `#333333` on a `#553333` background, which leads to nearly unreadable text for patches:

![screenshot_2017-01-10_11-34-49](https://cloud.githubusercontent.com/assets/19060/21819443/f0a5e03c-d728-11e6-8f3b-71b2309bf955.png)

Also, thanks for this theme! I'm enjoying it a lot lately!

**Comment by philiparvidsson** [comment]
Attempted a fix—get back to me if it doesn't look right. Thanks for enjoying the theme and creating issues! :smile:
